I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 307, in script
    $ gs.yojimbo_imprisioned_date      = current_day
  File "game/script.rpy", line 307, in <module>
    $ gs.yojimbo_imprisioned_date      = current_day
NameError: name 'current_day' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 307, in script
    $ gs.yojimbo_imprisioned_date      = current_day
  File "C:\Users\jishe\Desktop\New folder (3)\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jishe\Desktop\New folder (3)\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 307, in <module>
    $ gs.yojimbo_imprisioned_date      = current_day
NameError: name 'current_day' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Drilonis 1.0
Tue Jul  8 09:36:34 2025
